import java.util.Date;
import hello.world.model.Student;

rule "date before validation"
	when
		student: Student(null != joiningDate && joiningDate.before(new Date()))
	then
		String result = String.format("student name %s, age %s, joining date %s", student.getName()
		 ,student.getAge(), student.getJoiningDate());
		System.out.println(result);
end

rule "date after validation"
	when
		student: Student(null != joiningDate && joiningDate.after(new Date()))
	then
		String result = String.format("student name %s, age %s, joining date %s", student.getName()
		 ,student.getAge(), student.getJoiningDate());
		System.out.println(result);
end

rule "test"
	when
		student2: Student()
		student: Student(null != student2.joiningDate && student2.joiningDate.after(new Date()))
	then
		System.out.println("testing testing");
end