package rules;

import hello.world.model.Student;
import hello.world.StudentAgeValidation;

global StudentAgeValidation studentAgeValidation;

rule "is student name present"
	dialect "mvel"
	when
		Student(name == null)
	then
		System.out.println("student name does not exist");
end

rule "Age greater than 21"
	dialect "mvel"
	when
		s: Student( isAgeGreaterThan21() )
	then
		studentAgeValidation.printMessage(s.getName(), s.getAge().toString(), "Age is greater than 21");
end

rule "Age less than 15"
	dialect "mvel"
	when
		s: Student(isAgeLessThan15())
	then
		studentAgeValidation.printMessage(s.getName(), s.getAge().toString(), "Age is less than 15");
end

rule "Correct Age"
	dialect "mvel"
	when 
		s: Student( !isAgeGreaterThan21() && !isAgeLessThan15())
	then
		studentAgeValidation.printMessage(s.getName(), s.getAge().toString(), "Correct age");
end