package rules;

import hello.world.model.Student;
import hello.world.StudentAgeValidation;

global StudentAgeValidation studentAgeValidation;

rule "Age greater than 21"
	dialect "mvel"
	when
		Student( isAgeGreaterThan21() )
	then
		studentAgeValidation = new StudentAgeValidation();
		studentAgeValidation.printMessage("Age is greater than 21");
end

rule "Age less than 15"
	dialect "mvel"
	when
		Student(isAgeLessThan15())
	then
		System.out.println("Age is less than 15");
end

rule "Correct Age"
	dialect "mvel"
	when 
		Student( !isAgeGreaterThan21() && !isAgeLessThan15())
	then
		System.out.println("Correct age");
end